apiVersion: v1
kind: Service
metadata:
  name: {{ include "hearth.fullname" . }}-docs
  labels:
    {{- include "hearth.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.docs.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hearth.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: docs
